import express from "express";
export var API = express;
export var Application = API();
export var Router = API.Router;
import compression from "compression";
export var Compression = compression;
import axios from "axios";
export var Axios = axios;
import octokit from "octokit";
export var Octokit = octokit;
import database from "mongodb";
export var Database = database;
import orm from "mongoose";
export var ORM = orm;
