"use strict";
exports.__esModule = true;
exports.ORM = exports.Database = exports.Octokit = exports.Axios = exports.Compression = exports.Router = exports.Application = exports.API = void 0;
var tslib_1 = require("tslib");
var express_1 = (0, tslib_1.__importDefault)(require("express"));
exports.API = express_1["default"];
exports.Application = (0, exports.API)();
exports.Router = exports.API.Router;
var compression_1 = (0, tslib_1.__importDefault)(require("compression"));
exports.Compression = compression_1["default"];
var axios = (0, tslib_1.__importStar)(require("axios"));
exports.Axios = axios["default"];
var octokit = (0, tslib_1.__importStar)(require("octokit"));
exports.Octokit = octokit;
var database = (0, tslib_1.__importStar)(require("mongodb"));
exports.Database = database;
var orm = (0, tslib_1.__importStar)(require("mongoose"));
exports.ORM = orm;
