import * as Framework from "express";
export var Application = Framework.application;
export var Router = Framework.Router;
import { default as compression } from "compression";
export var Compression = compression;
import * as axios from "axios";
export var Axios = axios["default"];
import * as octokit from "octokit";
export var Octokit = octokit;
import * as database from "mongodb";
export var Database = database;
import * as orm from "mongoose";
export var ORM = orm;
